spring.application.name=fintech-app
spring.datasource.url=jdbc:postgresql://localhost:5432/fintechdb
spring.datasource.username=postgres
spring.datasource.password=190309
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.security=DEBUG
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
